# Generated by Django 6.0.2 on 2026-02-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, help_text='The News API source identifier.', max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('url_to_image', models.URLField(blank=True, default='', max_length=2000)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('content', models.TextField(blank=True, default='')),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.source')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='idx_category_pub'), models.Index(fields=['source_name', '-published_at'], name='idx_source_pub'), models.Index(fields=['country', '-published_at'], name='idx_country_pub'), models.Index(fields=['-published_at'], name='idx_published_desc'), models.Index(fields=['url'], name='idx_article_url')],
            },
        ),
    ]
